# Font
font_family JetBrains Mono Nerd Font
font_size 11.0

# Opacidade da janela e cor
background_opacity 0.6
background #020617

# Cursor
cursor_shape beam
cursor_trail 1

# Padding (entre o conteúdo e as bordas)
window_padding_width 8
background_blur 0

# Shell change (tipo de shell)
shell /usr/bin/zsh