#################
### AUTOSTART ### --- Aplicativos de inicialização
#################

# --- Autostart Softwares ---
# exec-once = $terminal
# exec-once = nm-applet &
exec-once = waybar
exec-once = wl-paste --type text --watch cliphist store # Control v (texto)
exec-once = wl-paste --type image --watch cliphist store # Control v (imagem)
exec-once = firefox
exec-once = hypridle # verifica o tempo idle e chama o hyprlock
exec-once = dunst
exec-once = awww-daemon & # inicia o awww-daemon que troca os wallpapers
exec-once = ~/.config/automate/startpc.sh # inicia o setup do pc automaticamente

# Outros dois managers de wallpaper caso queira utilizá-los
# exec-once = hyprpaper
# exec-once = swaybg -i ~/Wallpapers/osascokkkkk.png -m fill