###################
### MY PROGRAMS ### --- Configuração de programas
###################

# --- Programs ---
$terminal = kitty
$fileManager = dolphin
$menu = ~/.config/rofi/launchers/type-6/launcher.sh
Alt = ALT
Tab = TAB