##############################
### WINDOWS AND WORKSPACES ### --- Janelas e Ambientes
##############################

# --- Windows Config ---

# Ignora pedidos de maximização da janela (ou quando você clica no botão de maximizar da janela)
windowrule {
    name = suppress-window-maximize
    match:class = .*

    suppress_event = maximize # O evento a ser calado (suppress) é a maximização (maximize)
}

# Arruma alguns bugs de janela, como roubo de foco (nocofus) e dragging
windowrule {
    name = fix-xwayland-drags
    match:class = ^$
    match:title = ^$
    match:xwayland = true
    match:float = true
    match:fullscreen = false
    match:pin = false

    no_focus = true
}


# --- Windows Rules ---

# Garante que a waybar não flutue ou interfira com a tela cheia
windowrule {
    name = waybar-no-floating
    match:class = ^(waybar)$

    no_focus = true
    no_anim = true
    no_blur = true
}

# --- Workspaces ---
workspace = 1
workspace = 2
workspace = 3
workspace = 4
workspace = 5

# Os cinco (5) workspaces foram configurados para carregar assim que o computador iniciar (waybar).