# --- Hyprland Directory Parts ---
$hyprhouse = ~/.config/hypr/hyprland





################
### MONITORS ### --- Monitores
################

source = $hyprhouse/monitors.conf



###################
### MY PROGRAMS ### --- Configuração de programas
###################

source = $hyprhouse/myprograms.conf



#################
### AUTOSTART ### --- Aplicativos de inicialização
#################

source = $hyprhouse/autostart.conf



#############################
### ENVIRONMENT VARIABLES ###
#############################

source = $hyprhouse/environments.conf



###################
### PERMISSIONS ### --- Permissões
###################

source = $hyprhouse/permissions.conf



#####################
### LOOK AND FEEL ### --- Hyprland Visual
#####################

source = $hyprhouse/appearance.conf



#############
### INPUT ### --- Configuração do teclado
#############

source = $hyprhouse/keyboardinput.conf



###################
### KEYBINDINGS ### --- Atalhos
###################

source = $hyprhouse/keybinds.conf



##############################
### WINDOWS AND WORKSPACES ### --- Janelas e Ambientes
##############################

source = $hyprhouse/workspaces.conf





##################
### WIKIPEDIAS ###
##################

# Monitors: https://wiki.hypr.land/Configuring/Monitors/
# My Programs: https://wiki.hypr.land/Configuring/Keywords/
# Environment Variables: https://wiki.hypr.land/Configuring/Environment-variables/
# Permissions: https://wiki.hypr.land/Configuring/Permissions/
# Look and Feel: https://wiki.hypr.land/Configuring/Variables/
# Input: https://wiki.hypr.land/Configuring/Variables/#input
# Keybindings: https://wiki.hypr.land/Configuring/Keywords/
# Windows and Workspaces Rules: https://wiki.hypr.land/Configuring/Window-Rules/ (windows), https://wiki.hypr.land/Configuring/Workspace-Rules/ (workspaces)