# █ █ █▄█ █▀█ █▀█ █   █▀█ █▀▀ █▄▀
# █▀█  █  █▀▀ █▀▄ █▄▄ █▄█ █▄▄ █ █

# --- Geral ---
general {
    no_fade_in = false
    grace = 0
    disable_loading_bar = false
}

# --- Background ---
background {
    monitor = # Vazio = todos os monitores
    path = ~/Wallpapers/outtheworld.png
    blur_passes = 1
    blur_size = 2
    contrast = 0.8916
    brightness = 0.8172
    vibrancy = 0.1696
    vibrancy_darkness = 0.0
}

# --- Horas ---
label {
    monitor =
    text = cmd[update:1000] echo "<span>$(date +"%I")</span>"
    color = rgba(255, 255, 255, 1)
    font_size = 125
    font_family = StretchPro
    position = 0, 200
    halign = center
    valign = center
}

# --- Minutos ---
label {
    monitor =
    text = cmd[update:1000] echo "<span>$(date +"%M")</span>"
    color = rgb(38, 76, 124)
    font_size = 125
    font_family = StretchPro
    position = 0, 70
    halign = center
    valign = center
}

# --- Data ---
label {
    monitor =
    text = cmd[update:1000] echo -e "$(date +"%d %B, %a.")"
    color = rgba(255, 255, 255, 100)
    font_size = 22
    font_family = Suisse Intl Mono
    position = 0, -8
    halign = center
    valign = center
}

# --- Foto de perfil ---
image {
    monitor =
    path = ~/Profiles/justunderstand.jpg
    border_size = 3
    border_color = rgb(38, 76, 124)
    size = 100
    rounding = -1 # -1 = círculo perfeito
    rotate = 0
    position = 0, -130
    halign = center
    valign = center
}

# --- Usuário ---
label {
    monitor =
    text =     $USER
    color = rgba(216, 222, 233, 0.80)
    font_size = 22
    font_family = SF Pro Display Bold
    position = 0, -220
    halign = center
    valign = center
}

# --- Campo de senha ---
input-field {
    monitor =
    size = 300, 60
    outline_thickness = 2
    dots_size = 0.2
    dots_spacing = 0.2
    dots_center = true
    outer_color = rgba(0, 0, 0, 0)
    inner_color = rgba(255, 255, 255, 0.1)
    font_color = rgb(200, 200, 200)
    fade_on_empty = false
    font_family = SF Pro Display Bold
    placeholder_text = <i><span foreground="##ffffff99">🔒 Password </span></i>
    hide_input = false
    position = 0, -310 # Movido pra baixo pra dar espaço pra foto
    halign = center
    valign = center
}

# --- Música tocando ---
label {
    monitor =
    text = cmd[update:1000] echo "$(~/.config/hypr/hyprland/scripts/songdetail.sh)"
    color = rgb(38, 76, 124)
    font_size = 18
    font_family = JetBrains Mono Nerd, SF Pro Display Bold
    position = 0, 20
    halign = center
    valign = bottom
}