# --- Geral ---
general {
    lock_cmd = pidof hyprlock || hyprlock # pidof hyprlock verifica se o hyprlock está ativo, se não estiver, ativa (|| hyprlock)
    before_sleep_cmd = loginctl lock-session # Bloqueia a sessão atual no suspend (garante que você tenha que por a senha novamente para entrar)
    after_sleep_cmd = hyprctl dispatch dpms on # Força o monitor ligar se o Pc acordar após acordar do suspend (dpms é a energia do monitor)
}

# --- Listener's ---
listener {
    timeout = 900 # After 15 minutes
    on-timeout = pidof hyprlock || hyprlock # Run hyprlock
}

listener {
    timeout = 1200 # After 20 minutes
    on-timeout = hyprctl dispatch dpms off # Turn off the monitor
    on-resume = hyprctl dispatch dpms on # If it detects any activity (mouse or keyboard movement), turn on the monitor

    # Dispatch dpms = dispatch é "executar" e dpms é "Sinalização de Gerenciamento de Energia da Tela" (Display Power Management Signaling).
    # Você pode usar isso para monitores: ON para ligar o monitor, OFF para desligar e TOGGLE para alternar o modo
}

listener {
    timeout = 1500 # After 25 minutes
    on-timeout = systemctl suspend # Turn off the Pc (just the system)
}